#!/bin/bash
vi /etc/yum.repos.d/nginx.repo
[nginx]
name=nginx repo
baseurl=http://nginx.org/packages/mainline/rhel/7/$basearch/
gpgcheck=0
enabled=1
:wq!

sudo yum install nginx

sudo systemctl enable nginx

sudo systemctl start nginx
sudo systemctl stop nginx
sudo systemctl restart nginx
sudo systemctl status nginx

nano /usr/share/nginx/html/index.html

sudo amazon-linux-extras install epel -y
sudo yum install stress -y

aws s3 sync s3://wirldrydes-us-east-1/WebApplication/1_StaticWebHosting/website s3://www.dadu.yza --region us-east-1



aws s3 sync s3://wirldrydes-us-east-1/WebApplica1tion/1_StaticWebHosting/website s3://www.dadu.yza --region us-east-1

HOW R U
where r u
hi

